name: interpreter
description: A simple arithmetics interpreter.
publish_to: none
version: 0.0.1
environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"
dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
